---
title: "Introduction to BIKER"
author: "Craig Brinkerhoff"
date: "February 25, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

BIKER enables estimation of the normalized riverine gas exchange velocity from measurements of river surface width and slope. It does so using Bayesian inference and a Hamiltonian Monte Carlo sampler to generate a posterior distribution for a gas exchange upscaling model. BIKER was developed in the context of the NASA/CNES/UKSA/CSA SWOT mission (https://swot.jpl.nasa.gov/mission/overview/). The academic manuscript associated with this model development and validation is in preperation.

To run BIKER, the following workflow is ideal. Note that BIKER follows standard hydrology workflow for the discretization of the river observations along a mass-conserved river reach. This means that matrix rows represent spatial steps along the reach while matrix columns represent timesteps for these observations.

## Installation
BIKER is always under active development and the working version is available on GitHub. Follow [this link](https://github.com/craigbrinkerhoff/BIKER) to download.

## Workflow
#### Inputs
BIKER requires 3 inputs: <br>
- $Wobs$: a matrix of water surface widths <br>
- $Sobs$: a matrix of water surface slopes <br> 
- $dAobs$: a matrix of 'change in cross-sectional channel areas'. This must be approximated by the user. We generally assume a rectangular river channel so that this can be calculated as the following: $width*\delta H$.

#### Run BIKER
The following is the series of fuctions that need to be run to use BIKER. See the references tab for more information about the function options. <br>

```
reach_data <- biker_data(w=Wobs, s=Wobs, da=dAobs) #collect data into object the algorithm can read
reach_priors <- biker_priors(reach_data) #estimate prior hyperparameters for Bayesian inference
k600_estimates <- biker_estimate(reach_data, reach_priors) #sample from joint posterior distribution
```

#### Manually specifying prior hyperparameters
Priors can also be overwritten manually if you so desire. This is done as following, for example, for the A0_hat prior which has a value for every spatial step in the river reach:
```
reach_priors <- biker_priors(reach_data, logA0_hat = rep(5000, ncol(W_obs)))
```

If you want the full list of customizable prior hyperparameters, run the following:
```
prior_settings()
```
